### ISSUE TITLE
Make the repository public

### ISSUE THREAD

**Issue by Hespian** [kamping-site/kamping#84]
The current plan is to make this repo public once the "Proof of Concept v0.1.0" milestone is finished.

Here is a (probably incomplete) list of thing to **before** switching to public:
- [x] Move project to [kamping-site](https://github.com/kamping-site)
- [x] Update Readme
- [x] Update "About" section
- [x] Decide on a license (#49) 
- [x] Change workflows to run on GitHub hosted runners (#719)
- [x] Somehow make it impossible to use the self-hosted runner (so nobody can make a malicious pull request that runs on our server)
- [ ] Re-enable Intel compilers, Intel MPI and mpich (#78 )
- [ ] Add macOS build
- [x] Auto-generate documentation and publish it on GitHub pages (see #79 )
- [x] Change merge guidelines (external contributors can't merge themselves) - also probably move this to a new `contributing.md` (see #424 )

Things that can only be done **after** switching to public:
- [ ] Add branch protection rules:
    - [x] Disable (force) push to main
    - [x] Require at least one approving review/no review requesting changes before merging
    - [x] Require all checks to pass before merging
    - [x] Require all conversations to be resolved before merging
    - [ ] (Maybe) Use "Require linear history" feature
    - [ ] (Maybe) Use "Require merge queue" feature - It seems like this will always use fast-forward instead of squash
