### ISSUE TITLE
In/Exclusive_scan

### ISSUE THREAD

**Issue by niklas-uhl** [kamping-site/kamping#9]
- useful default on rank 0
- same requirements on buffers as other collectives

@lukashuebner: Planned PRs/tasks
- [x] Add scan wrapper (no need for identities) without MINLOC and MAXLOC (#358)
- [x] Add exscan wrapper without MINLOC and MAXLOC but including identities for the other operations (#379 )
- [ ] Add `scan_single()` and `exscan_single()` (#392)
- ~~Add identities for custom operations~~ (let's see if somebody needs it)
